#!/bin/bash

percent=$(cat /sys/firmware/picocalc/battery_percent)
if [[ ${percent} -gt 100 ]]; then
	if [[ -t 1 ]]; then
	       echo "plugged"
	else
		if [[ ${percent} -ge 228 ]]; then
			echo -n 'F'
		else
			echo -n 'C'
		fi
	fi
else
	[[ -t 1 ]] && echo "unplugged" 
fi

# EOF
